services:
  url-shortener:
    build: .
    ports:
      - "8000:8000"
    volumes:
      # Mount the entire data directory for database persistence
      - ./data:/app/data
    environment:
      - DATABASE_PATH=/app/data/url_shortener.db

